version: '3.8'

services:
  mysql:
    env_file:
      - ../env/.env.prod
    volumes:
      - /var/lib/pc_mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    ports:
      - "6379:6379"

  spring-app:
    env_file:
      - ../env/.env.prod
    ports:
      - "8080:8080"

