version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: price_comparison_mysql
    restart: always
    env_file:
      - ../env/.env.local
    ports:
      - "3306:3306"
    volumes:
      - ../docker/mysql/data:/var/lib/mysql
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 20s

  redis:
    image: redis:7.0
    container_name: price_comparison_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app_network

  spring-app:
    profiles: ["disable"]
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: price_comparison_spring
    restart: always
    env_file:
      - ../env/.env.local
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ../logs:/app/logs

networks:
  app_network:
    driver: bridge
