version: '3.8'

services:
  spring-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: price_comparison_spring
    restart: always
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - ../env/.env.prod
    ports:
      - "8080:8080"
    networks:
      - app_network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - ../logs:/app/logs

